import { flexConfig } from "../shared/pricing.ts";
export const categories = [
  { id: "all", name: "All insurance", short: "All" },
  {
    id: "motor",
    name: "Motor",
    short: "Motor",
    description: "For the roads you take.",
    base: 2400000,
    limit: "Vehicle value up to ₭200 million",
    coverage: "Own damage and third-party liability",
    exclusion: "Commercial use, wear and tear",
    deductible: "₭1,000,000 per own-damage claim",
  },
  {
    id: "health",
    name: "Health",
    short: "Health",
    description: "Put your wellbeing first.",
    base: 3600000,
    limit: "Annual limit up to ₭150 million",
    coverage: "Inpatient treatment and hospital care",
    exclusion: "Pre-existing conditions, elective treatment",
    deductible: "₭500,000 per admission",
  },
  {
    id: "travel",
    name: "Travel",
    short: "Travel",
    description: "Go further. Worry less.",
    base: 24000,
    limit: "Emergency medical up to ₭300 million",
    coverage: "Overseas emergencies and trip disruption",
    exclusion: "High-risk sports, known travel disruptions",
    deductible: "₭250,000 per claim",
  },
  {
    id: "property",
    name: "Home & property",
    short: "Property",
    description: "Protect your place in the world.",
    base: 1800000,
    limit: "Building value up to ₭500 million",
    coverage: "Fire, storm and damage to your home",
    exclusion: "Gradual deterioration, unoccupied property",
    deductible: "₭1,000,000 per claim",
  },
  {
    id: "life",
    name: "Life & family",
    short: "Life",
    description: "Think about their tomorrow.",
    base: 2100000,
    limit: "Benefit up to ₭200 million",
    coverage: "Term life benefit for nominated beneficiaries",
    exclusion: "Misrepresentation and excluded activities",
    deductible: "No deductible in this demonstration",
  },
  {
    id: "accident",
    name: "Personal accident",
    short: "Accident",
    description: "A little backup for the unexpected.",
    base: 480000,
    limit: "Accident benefit up to ₭100 million",
    coverage: "Accidental injury and disability benefits",
    exclusion: "Intentional injury, hazardous occupations",
    deductible: "₭100,000 medical excess",
  },
  {
    id: "business",
    name: "Business & SME",
    short: "Business",
    description: "Keep your business moving.",
    base: 5400000,
    limit: "Combined limit up to ₭1 billion",
    coverage: "Business property and interruption",
    exclusion: "Cyber events, undisclosed activities",
    deductible: "₭2,000,000 per claim",
  },
  {
    id: "liability",
    name: "Liability",
    short: "Liability",
    description: "Confidence in your responsibilities.",
    base: 3200000,
    limit: "Liability limit up to ₭500 million",
    coverage: "Third-party bodily injury and property damage",
    exclusion: "Professional negligence, contractual penalties",
    deductible: "₭1,000,000 per claim",
  },
  {
    id: "cargo",
    name: "Cargo & transit",
    short: "Cargo",
    description: "Care for every delivery.",
    base: 1500000,
    limit: "Cargo value up to ₭250 million",
    coverage: "Accidental cargo loss during declared transit",
    exclusion: "Delay, inadequate packing, inherent vice",
    deductible: "1% of declared cargo value",
  },
  {
    id: "engineering",
    name: "Engineering",
    short: "Engineering",
    description: "Build with greater certainty.",
    base: 6500000,
    limit: "Contract value up to ₭2 billion",
    coverage: "Construction works and machinery damage",
    exclusion: "Defective design and normal wear",
    deductible: "₭5,000,000 per incident",
  },
  {
    id: "agriculture",
    name: "Agriculture",
    short: "Agriculture",
    description: "Support what you grow.",
    base: 950000,
    limit: "Declared crop value up to ₭100 million",
    coverage: "Named weather perils on declared crops",
    exclusion: "Poor husbandry, undeclared crops",
    deductible: "10% of eligible loss",
  },
  {
    id: "marine",
    name: "Marine & aviation",
    short: "Marine",
    description: "Protection beyond the everyday.",
    base: 9800000,
    limit: "Specialist limit up to ₭2 billion",
    coverage: "Declared hull damage and named liabilities",
    exclusion: "War, unlicensed operation, excluded routes",
    deductible: "2% of insured value",
  },
];
export const insurers = [
  { id: "demo-a", name: "Demo insurer A", initials: "A", color: "teal" },
  { id: "demo-b", name: "Demo insurer B", initials: "B", color: "blue" },
  { id: "demo-c", name: "Demo insurer C", initials: "C", color: "ochre" },
];
export const products = categories
  .filter((c) => c.id !== "all")
  .flatMap((c, index) =>
    [0, 1].map((tier) => ({
      id: `${c.id}-${tier ? "plus" : "essential"}`,
      category: c.id,
      name: `${c.name === "Motor" ? "Motor" : c.name === "Health" ? "Health" : c.name === "Travel" ? "Travel" : c.name} ${tier ? "Plus" : "Essential"}`,
      description: c.description!,
      insurerId: insurers[(index + tier) % insurers.length].id,
      insurer: insurers[(index + tier) % insurers.length].name,
      version: "demo-2026.2",
      ruleVersion: "demo-flex-pricing-2",
      flex: flexConfig(c.id, tier),
      synthetic: true,
      published: true,
      effectiveFrom: "2026-01-01",
      effectiveTo: "2099-12-31",
      basePremium: c.base! * (tier ? 1.5 : 1),
      period: c.id === "travel" ? "day" : "year",
      coverage: [
        c.coverage!,
        tier
          ? "Extended assistance and higher sublimits"
          : "Standard assistance service",
      ],
      limit: c.limit!,
      exclusion: c.exclusion!,
      deductible: c.deductible!,
      source: "Synthetic comparison fixture — not insurer-approved wording",
      eligibility:
        "Demonstration only: applicants aged 18–70. Real eligibility awaits insurer approval.",
      conditions:
        "Indicative demonstration quote only. No cover is bound by a quote, application or payment.",
      popular: tier === 0 && ["motor", "health", "travel"].includes(c.id),
    })),
  );
export type Product = (typeof products)[number];
